Initial commit for dynamic query
bloogrox/ssp-campaigns pull request #52
Opened 2017-07-29 16:04 UTC by ijharulislam

2017-07-29 16:29 UTC, bloogrox requested changes
thank you,

please look at the comments

2017-07-29 16:29 UTC, bloogrox commented on services/subscriber.py
> +            return [i.to_dict() for i in res.hits]
there must be `_id` inside every document, please look in old version

2017-07-29 16:29 UTC, bloogrox commented on services/subscriber.py
> +                           ): Q('terms', **{query["field"]: query["value"]})})
`terms` works with multiple values, 
```
"terms": {"field": []}
```
but if we have single value (in case `"=": "filter"`) we should use `term`

2017-07-29 16:29 UTC, bloogrox commented on services/subscriber.py
> +            logical_operator_mappings = {
i'm not sure this mapping will be correct,
all targeting must query as `and` clause, it is `must`

what if we use only `must` and `must_not`
and `=` kind of targetings with single value we convert to array and use `terms`

2017-07-29 19:17 UTC, bloogrox requested changes

2017-07-29 19:17 UTC, bloogrox commented on services/subscriber.py
> +            s = Search(using=es, index="subscribers")
`index="users"` was correct, it is an alias

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

2017-07-29 19:17 UTC, bloogrox commented on services/subscriber.py
> +                "operator": "AND",
I think we need to change operator `AND`

2017-07-29 20:42 UTC, bloogrox requested changes

2017-07-29 20:42 UTC, bloogrox commented on services/subscriber.py
>              s.extra(size=volume, boost_mode='replace')
to set a `size` we do 

```
s = s[volume]
```

http://elasticsearch-dsl.readthedocs.io/en/latest/search_dsl.html?highlight=size#pagination

2017-07-30 11:56 UTC, bloogrox commented on services/subscriber.py
>              s.extra(size=volume, boost_mode='replace')
please don't forget this line

2017-07-30 11:59 UTC, ijharulislam commented on services/subscriber.py
>              s.extra(size=volume, boost_mode='replace')
I think, s.extra(size=limit) works fine. I used it in my other Django project. Do you think, I have to change it?

2017-07-30 12:14 UTC, bloogrox commented on services/subscriber.py
>              s.extra(size=volume, boost_mode='replace')
this code (with `.extra(size=)`)
```
client = Elasticsearch(["http://localhost:9200"])

targetings = [
    {
        "field": "a",
        "operator": "IN",
        "value": [10, 5, 1, 2, 3]
    }
]

s = Search(using=client, index="subs")

s.extra(size=666)

logical_operator_mappings = {
    'IN': 'must',
    'NOT IN': 'must_not',
}

q = Q()

for query in targetings:
    bool_q = Q('bool',
                **{logical_operator_mappings.get(
                    query.get('operator')
                ): Q('terms', **{query["field"]: query["value"]})})
    q += bool_q

s = s.query(q)

s.query = dslq.FunctionScore(
    query=s.query,
    functions=[dslq.SF('random_score')],
    boost_mode="replace"
    )

# s = s[1]

print(s.to_dict())
```
produces this output 
```
{'query': {'function_score': {'query': {'bool': {'must': [{'terms': {'a': ['10', '5', 1, 2, 3]}}]}}, 'functions': [{'random_score': {}}], 'boost_mode': 'replace'}}}
```
nothing about pagination


and if I use index operator `[]`
```
s = s[1]
print(s.to_dict())
```
then it adds `size`
```
{'query': {'function_score': {'query': {'bool': {'must': [{'terms': {'a': [10, 5, 1, 2, 3]}}]}}, 'functions': [{'random_score': {}}], 'boost_mode': 'replace'}}, 'from': 1, 'size': 1}
```
why is it so..

you can examine yourself the query with `print(s.to_dict())`

may be it's version issue ?
```
elasticsearch (5.4.0)
elasticsearch-dsl (5.3.0)
```

2017-07-30 12:33 UTC, ijharulislam commented on services/subscriber.py
>              s.extra(size=volume, boost_mode='replace')
Okay. I will am adding slicing as a pagination.

2017-07-30 12:47 UTC, bloogrox requested changes
the last thing Ijhar, 
let's use fork, for the boost_mode, 
and we are done

2017-07-30 12:47 UTC, bloogrox commented on requirements.txt
> +elasticsearch-dsl>=5.0.0,<6.0.0
the last thing,
let's use forked version
git+https://github.com/bloogrox/elasticsearch-dsl-py@boost-mode

2017-07-30 14:37 UTC, bloogrox approved these changes

2017-07-30 14:39 UTC, bloogrox commented
thank you, that was great, i'll merge it in a few hours

2017-07-30 19:33 UTC, merged